### ISSUE TITLE
Add Pundit description in README

### ISSUE THREAD

**Issue by StephanMeijer** [code-and-effect/effective_trash#1]
In the README I can find a description for cancan, but not for Pundit

**Comment by matt-riemer** [comment]
Yea this is a good add. I've done this for other effective gems, but not trash hmm!

**Comment by matt-riemer** [comment]
I don't actually use Pundit, does instructions like these make sense? :)

https://github.com/code-and-effect/effective_datatables#authorization

**Comment by StephanMeijer** [comment]
This format'd be great!
